### ISSUE TITLE
运行前端开发服务器，不起作用

### ISSUE THREAD

**Issue by lewis-ing** [gozeon/yapii#10]
大神，我分别使用前端和后端指令进行启动服务的时候，现在网页可以打开，页面显示内容全都都是文件信息，
输入地址：http://127.0.0.1:4000/
![image](https://github.com/user-attachments/assets/faaba4a3-2b87-43ab-ae26-db13c9f4f360)

分别执行指令(都正常运行)：
后端服务启动：`npm run dev-server`
前端服务启动：`npm run dev-client`

或者使用启动指令：
运行开发服务器： `npm run dev`

浏览器输入地址后，页面显示内容如上图。

**Comment by gozeon** [comment]
他这个前端开发工具我也没研究，我本地开发是启的server，然后前端每次都编译一下.


### 启动node
```npm
npm start
```

### 编译前端
```npm
npm run build-client
```

**Comment by lewis-ing** [comment]
非常感谢大神！
