### ISSUE TITLE
部署在生产环境，怎么调试本地启动的api

### ISSUE THREAD

**Issue by olajowon** [gozeon/yapii#11]
大佬，部署在生产环境，怎么调试本地启动的api
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/71ba26fe-c494-46c7-bffb-88c952f1a3bf">

_Originally posted by @olajowon in https://github.com/gozeon/yapii/issues/4#issuecomment-2502658556_

**Comment by gozeon** [comment]
你使用127这个IP，那不访问到了生成环境机器了么，，，

方法 1. 假设 yapi部署环境为A，环境A能访问到环境B，你需要做的是把代码部署到环境B。
方法 2. 模拟`api/run/add`接口，本地起一个axios转发服务 S ([代码参考](https://github.com/gozeon/yapii/blob/master/server/controllers/run.js))，charles劫持浏览器请求到 S。
