### ISSUE TITLE
windows下npm install报错

### ISSUE THREAD

**Issue by putao520** [gozeon/yapii#3]
## 版本号
~ 最新版

## 什么问题
~ windows上NPM安装报错

## 如何复现此问题
~  node v20+的windows下,git clone 后直接npm出错

**Comment by putao520** [comment]
package.json依赖一大堆版本冲突的...

**Comment by gozeon** [comment]
> package.json依赖一大堆版本冲突的...

贴一下报错信息，建议`--verbose`输出详细信息。

如果你不需要二次开发，直接`npm install --production`

**Comment by putao520** [comment]
大佬,我需要二次开发啊.现在yapii以前的调试接口的插件坏了不能用了,或者能留个即时聊天工具吗?discard或者微信什么的?

**Comment by putao520** [comment]
大概就是里面很多包没有更新了,但是引入的包版本与从项目里的包版本不匹配.感觉是炸了NPM最大的屎坑了(版本依赖冲突)了

**Comment by gozeon** [comment]
额，js的开发，90%的问题来自`node_module`，这个项目也是。

**Comment by gozeon** [comment]
> 大佬,我需要二次开发啊.现在yapii以前的调试接口的插件坏了不能用了,或者能留个即时聊天工具吗?discard或者微信什么的?

需要二次开发，用项目里的`Dockerfile`吧，`node-sass`老版在windows需要配置各种

**Comment by putao520** [comment]
好吧,谢谢,我得修理我windows上的wsl2了..

**Comment by gozeon** [comment]
> 好吧,谢谢,我得修理我windows上的wsl2了..

建议使用docker，因为这个项目太老了，如果开发其他项目，环境还需变

**Comment by putao520** [comment]
我打算加个客户端,他原来的运行API就必须要插件,限制太多了.但是相对来说他比什么apifox好用多了,我也没办法.

**Comment by gozeon** [comment]
> 大佬,我需要二次开发啊.现在yapii以前的调试接口的插件坏了不能用了,或者能留个即时聊天工具吗?discard或者微信什么的?

cross-request插件问题可参考 https://github.com/gozeon/yapii/issues/4#issuecomment-2022276480
