### ISSUE TITLE
作者你好，cross-request插件chrome好像不支持了，有替代方案么

### ISSUE THREAD

**Issue by kirito41dd** [gozeon/yapii#4]

**Comment by gozeon** [comment]
额，之前没用到过这个功能，看了一下，目前能想到的就是使用`child_process`代替插件，但还在犹豫要不要修改

**Comment by gozeon** [comment]
功能已增加，获取最新代码可查看

![image](https://github.com/gozeon/yapii/assets/17582116/94b818f5-7a71-4f08-96e7-1abfdd5fd1ca)

**Comment by olajowon** [comment]
大佬，部署在生产环境，怎么调试本地启动的api
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/71ba26fe-c494-46c7-bffb-88c952f1a3bf">
