### ISSUE TITLE
版本咨询

### ISSUE THREAD

**Issue by zengshuaishuai** [gozeon/yapii#7]
## 什么问题
你本地开发 nodejs使用的哪个版本

## 如何复现此问题
~ 

> 最好有简单的例子，因为很多功能暂时没用过或不会用~

**Comment by gozeon** [comment]
`node12`，我用的docker环境，你可以看一下[dockerfile](https://github.com/gozeon/yapii/blob/master/Dockerfile)

**Comment by gozeon** [comment]
额，这里面还涉及npm镜像问题，直接看 https://github.com/gozeon/yapii?tab=readme-ov-file#develop 吧
