### ISSUE TITLE
windows使用npm install卡死

### ISSUE THREAD

**Issue by lewis-ing** [gozeon/yapii#9]
## windows使用npm install卡死
1、没有删除package-lock.json文件，使用npm install,一直不动了
2、node 版本：v18.20.4
3、安装卡死图

![image](https://github.com/user-attachments/assets/917fa315-6ec8-412c-b3f5-ba48dff56317)

**Comment by gozeon** [comment]
这个日志输出不准确，使用`npm install --verbose` ，你就能看到具体问题了。

> 因为早期sass的原因，不建议使用win作为开发环境，建议docker吧

**Comment by lewis-ing** [comment]
![image](https://github.com/user-attachments/assets/eec896c7-d842-4205-9e51-794374f506a5)
使用```npm install --verbose``` 指令，好像 https://registry.nlark.com/@types/minimist/download/@types/minimist-1.2.2.tgz?cache=0&sync_timestamp=1629708337116&other_urls=https%3A%2F%2Fregistry.nlark.com%2F%40types%2Fminimist%2Fdownload%2F%40types%2Fminimist-1.2.2.tgz 这个无法下载，怎么解决

**Comment by gozeon** [comment]
要么把 `package-lock.json` 里的地址换掉，要么把 `npm` 版本降低下

**Comment by gozeon** [comment]
如果你需要二次开发的话，还是建议你用docker或者装一个node12版本，清掉之前npm缓存

**Comment by gozeon** [comment]
如果你运行的话，使用`npm install --production` ，node 18也可以。

> 还是不要把时间浪费在这些历史问题上

**Comment by lewis-ing** [comment]
已经可以，使用的命令是 `npm install --force`(已删除package-lock.json),感谢大神。还有一个问题，我没有找到导入swagger.json文件的接口，是否能给提供一下？

**Comment by gozeon** [comment]
进入项目，有个`数据管理`的按钮，就在`接口`那一排，不过我没用过，不会`swagger`..

**Comment by lewis-ing** [comment]
OK,Thx
